from jinja2 import Template
import os

LAUNCH_TEMPLATE = """<?xml version="1.0"?>
<launch>
    <!-- Autogenerated MAVROS node for {{ drone.name }} -->
    <node pkg="mavros" type="mavros_node" name="{{ drone.node_name }}" output="screen">
        <!-- Standard GazeboSim PX4 connection -->
        <param name="fcu_url" value="udp://:14540@{{ drone.ip_address }}:14580" />
        <param name="gcs_url" value="" />
        <param name="tgt_system" value="{{ drone.system_id }}" />
        <param name="tgt_component" value="1" />
        <param name="fcu_protocol" value="v2.0" />
        
        <!-- PX4 parameters for GazeboSim -->
        <param name="pluginlists_yaml" value="$(find mavros)/launch/px4_pluginlists.yaml" />
        <param name="config_yaml" value="$(find mavros)/launch/px4_config.yaml" />
    </node>
</launch>
"""

def generate_launch_file(drone):
    """Генерирует launch-файл для подключения к дрону в GazeboSim"""
    template = Template(LAUNCH_TEMPLATE)
    content = template.render(drone=drone)
    
    os.makedirs('launch_files', exist_ok=True)
    with open(f'launch_files/{drone["name"]}.launch', 'w', encoding='utf-8') as f:
        f.write(content)